# Generated by Django 3.0 on 2019-12-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='description',
            field=models.CharField(default=1, max_length=280),
            preserve_default=False,
        ),
    ]
