# Generated by Django 3.0 on 2019-12-07 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superStore_website', '0002_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
